skip_undocumented: true

include:
  - "/**/Worker/ConstructorIO.swift"
  - "/**/Request/*Query.swift"
  - "/**/Request/Builder/*QueryBuilder.swift"
  - "/**/Result/Responses/*.swift"
  - "/**/Result/*.swift"
  - "/**/Config/ConstructorIOConfig.swift"

custom_categories:
  - name: Client
    children:
      - ConstructorIOConfig
      - ConstructorIO
  - name: Result Request Structures
    children:
      - CIOAutocompleteQuery
      - CIOBrowseQuery
      - CIOBrowseItemsQuery
      - CIOBrowseFacetsQuery
      - CIOBrowseFacetOptionsQuery
      - CIOBrowseGroupsQuery
      - CIORecommendationsQuery
      - CIOSearchQuery
      - CIOQuizQuery
  - name: Result Request Builders
    children:
      - CIOAutocompleteQueryBuilder
      - CIOBrowseQueryBuilder
      - CIOBrowseItemsQueryBuilder
      - CIOBrowseFacetsQueryBuilder
      - CIOBrowseFacetOptionsQueryBuilder
      - CIOBrowseGroupsQueryBuilder
      - CIORecommendationsQueryBuilder
      - CIOSearchQueryBuilder
  - name: Response Structures
    children:
      - CIOAutocompleteResponse
      - CIOBrowseResponse
      - CIOBrowseFacetsResponse
      - CIOBrowseFacetOptionsResponse
      - CIORecommendationsResponse
      - CIOSearchResponse
      - CIOQuizQuestionResponse
      - CIOQuizResultsResponse
  - name: Result Structures & Classes
    children:
      - CIOAutocompleteResult
      - CIOFilterFacet
      - CIOFilterFacetOption
      - CIOFilterGroup
      - CIOGroup
      - CIORecommendationsPod
      - CIORecommendationsStrategy
      - CIOResult
      - CIOResultData
      - CIOResultFacet
      - CIOSearchRedirectInfo
      - CIOSortOption
      - CIOQuizQuestion
      - CIOQuizOption
      - CIOQuizOptionAttribute
      - CIOQuizImages
      - CIOQuizResult
