# .slather.yml

scheme: AutocompleteClient
workspace: AutocompleteClient.xcworkspace
xcodeproj:  AutocompleteClient.xcodeproj
ignore: 
  - AutocompleteClientTests/*
  - AutocompleteClient/FW/UI/*
  - AutocompleteClient/Utils/**/UI*